#!/usr/bin/env php
<?php

use Hackingangle\Crack;
use Symfony\Component\Console\Application;

require './vendor/autoload.php';

$application = new Application("hackingangle攻击包", "1.0");
$application->add(new Crack());
$application->run();
