#!/usr/bin/env php
<?php

use Hackingangle\Crack;
use Symfony\Component\Console\Application;
use Symfony\Component\Console\Input\InputArgument;
use Symfony\Component\Console\Input\InputInterface;
use Symfony\Component\Console\Output\OutputInterface;

require './vendor/autoload.php';

$application = new Application("hackingangle攻击包", "1.0");
$application->register("ready")
    ->addArgument("host", InputArgument::OPTIONAL, '嗅探主机', 'baidu.com')
    ->setDescription("嗅探程序")
    ->setCode(function (InputInterface $input, OutputInterface $output) {
        $host = $input->getArgument('host');
        $output->writeln("嗅探主机:{$host}");
    });
$application->run();
